<?php

namespace App\Http\Requests;

use Illuminate\Foundation\Http\FormRequest;

class Character extends FormRequest
{
    /**
     * Determine if the user is authorized to make this request.
     *
     * @return bool
     */
    public function authorize()
    {
        return true;
    }

    /**
     * Get the validation rules that apply to the request.
     *
     * @return array
     */
    public function rules()
    {
        return [
            'character_name' => ['required', 'string', 'max:30'],
            'character_age' => ['required', 'numeric'],
            'character_title' => ['required', 'string', 'max:30'],
            'character_date_of_birth' => ['required', 'numeric', 'min:1', 'max:31'],
            'character_month_of_birth' => ['required', 'numeric', 'min:1', 'max:12'],
            'character_year_of_birth' => ['required', 'numeric'],
            'character_experience' => ['required', 'numeric'],
            'character_essence_game' => ['required', 'numeric'],
            'character_essence_total' => ['required', 'numeric'],

            'character_house_name' => ['required', 'string', 'max:30'],
            'character_house_rank' => ['required', 'string', 'max:30'],
            'character_house_dogma' => ['required', 'string', 'max:30'],

            'character_guild_name' => ['required', 'string', 'max:30'],
            'character_guild_dogma' => ['required', 'string', 'max:30'],

            'character_career_name' => ['required', 'string', 'max:30'],

            'character_career_physic' => ['required', 'numeric', 'min:1', 'max:9'],
            'character_career_physic_bonus' => ['numeric'],
            'character_career_physic_penalty' => ['numeric'],

            'character_career_mental' => ['required', 'numeric', 'min:1', 'max:9'],
            'character_career_mental_bonus' => ['numeric'],
            'character_career_mental_penalty' => ['numeric'],

            'character_career_reaction' => ['required', 'numeric', 'min:1', 'max:9'],
            'character_career_reaction_bonus' => ['numeric'],
            'character_career_reaction_penalty' => ['numeric'],

            'character_life_point_max' => ['required', 'numeric'],
            'character_life_point_game' => ['required', 'numeric'],
            'character_life_point_bonus' => ['numeric'],
            'character_life_point_percentage_bonus' => ['numeric'],

            'character_magic_point_max' => ['required', 'numeric'],
            'character_magic_point_game' => ['required', 'numeric'],
            'character_magic_point_bonus' => ['numeric'],
            'character_magic_point_percentage_bonus' => ['numeric'],

            'character_magic_force_arcana_max' => ['required', 'numeric'],
            'character_magic_force_arcana_game' => ['required', 'numeric'],
            'character_magic_force_arcana_bonus' => ['numeric'],
            'character_magic_force_arcana_percentage_bonus' => ['numeric'],

            'character_magic_force_holy_max' => ['required', 'numeric'],
            'character_magic_force_holy_game' => ['required', 'numeric'],
            'character_magic_force_holy_bonu' => ['numeric'],
            'character_magic_force_holy_percentage_bonus' => ['numeric'],

            'character_magic_force_cursed_max' => ['required', 'numeric'],
            'character_magic_force_cursed_game' => ['required', 'numeric'],
            'character_magic_force_cursed_bonus' => ['numeric'],
            'character_magic_force_cursed_percentage_bonus' => ['numeric'],

            'character_gold' => ['numeric'],
            'character_bank'=> ['numeric'],
            'character_lap_speed' => ['required', 'numeric'],

            'character_movement' => ['numeric'],
            'character_movement_bonus_humanTerritory' => ['numeric'],
            'character_movement_bonus_inside' => ['numeric'],
            'character_movement_bonus_savageTerritory' => ['numeric'],
            'character_movement_bonus_naval' => ['numeric'],
            'character_movement_bonus_mount' => ['numeric'],

            'character_fields' => ['numeric'],
            'character_fields_bonus_spell' => ['numeric'],

            'character_weapon1_name' => ['string'],
            'character_weapon1_type' => ['string'],
            'character_weapon1_scope' => ['numeric'],
            'character_weapon1_attack' => ['numeric'],
            'character_weapon1_attack_b' => ['numeric'],
            'character_weapon1_fumble' => ['numeric'],
            'character_weapon1_damage' => ['numeric'],
            'character_weapon1_dices' => ['string'],
            'character_weapon1_critic' => ['numeric'],
            'character_weapon1_face' => ['numeric'],
            'character_weapon1_flank' => ['numeric'],
            'character_weapon1_back' => ['numeric'],
            'character_weapon1_value' => ['numeric'],

            'character_weapon2_name' => ['string'],
            'character_weapon2_type' => ['string'],
            'character_weapon2_scope' => ['numeric'],
            'character_weapon2_attack' => ['numeric'],
            'character_weapon2_attack_b' => ['numeric'],
            'character_weapon2_fumble' => ['numeric'],
            'character_weapon2_damage' => ['numeric'],
            'character_weapon2_dices' => ['string'],
            'character_weapon2_critic' => ['numeric'],
            'character_weapon2_face' => ['numeric'],
            'character_weapon2_flank' => ['numeric'],
            'character_weapon2_back' => ['numeric'],
            'character_weapon2_value' => ['numeric'],

            'character_weapon3_name' => ['string'],
            'character_weapon3_type' => ['string'],
            'character_weapon3_scope' => ['numeric'],
            'character_weapon3_attack' => ['numeric'],
            'character_weapon3_attack_b' => ['numeric'],
            'character_weapon3_fumble' => ['numeric'],
            'character_weapon3_damage' => ['numeric'],
            'character_weapon3_dices' => ['string'],
            'character_weapon3_critic' => ['numeric'],
            'character_weapon3_face' => ['numeric'],
            'character_weapon3_flank' => ['numeric'],
            'character_weapon3_back' => ['numeric'],
            'character_weapon3_value' => ['numeric'],

            'character_weapon4_name' => ['string'],
            'character_weapon4_type' => ['string'],
            'character_weapon4_scope' => ['numeric'],
            'character_weapon4_attack' => ['numeric'],
            'character_weapon4_attack_b' => ['numeric'],
            'character_weapon4_fumble' => ['numeric'],
            'character_weapon4_damage' => ['numeric'],
            'character_weapon4_dices' => ['string'],
            'character_weapon4_critic' => ['numeric'],
            'character_weapon4_face' => ['numeric'],
            'character_weapon4_flank' => ['numeric'],
            'character_weapon4_back' => ['numeric'],
            'character_weapon4_value' => ['numeric'],

            'character_weapon5_name' => ['string'],
            'character_weapon5_type' => ['string'],
            'character_weapon5_scope' => ['numeric'],
            'character_weapon5_attack' => ['numeric'],
            'character_weapon5_attack_b' => ['numeric'],
            'character_weapon5_fumble' => ['numeric'],
            'character_weapon5_damage' => ['numeric'],
            'character_weapon5_dices' => ['string'],
            'character_weapon5_critic' => ['numeric'],
            'character_weapon5_face' => ['numeric'],
            'character_weapon5_flank' => ['numeric'],
            'character_weapon5_back' => ['numeric'],
            'character_weapon5_value' => ['numeric'],

            'character_armor1_name' => ['string'],
            'character_armor1_piercing' => ['numeric'],
            'character_armor1_edge' => ['numeric'],
            'character_armor1_blunt' => ['numeric'],
            'character_armor1_fire' => ['numeric'],
            'character_armor1_spell' => ['numeric'],
            'character_armor1_clutter' => ['numeric'],
            'character_armor1_magic' => ['numeric'],
            'character_armor1_value' => ['numeric'],

            'character_armor2_name' => ['string'],
            'character_armor2_piercing' => ['numeric'],
            'character_armor2_edge' => ['numeric'],
            'character_armor2_blunt' => ['numeric'],
            'character_armor2_fire' => ['numeric'],
            'character_armor2_spell' => ['numeric'],
            'character_armor2_clutter' => ['numeric'],
            'character_armor2_magic' => ['numeric'],
            'character_armor2_value' => ['numeric'],

            'character_armor3_name' => ['string'],
            'character_armor3_piercing' => ['numeric'],
            'character_armor3_edge' => ['numeric'],
            'character_armor3_blunt' => ['numeric'],
            'character_armor3_fire' => ['numeric'],
            'character_armor3_spell' => ['numeric'],
            'character_armor3_clutter' => ['numeric'],
            'character_armor3_magic' => ['numeric'],
            'character_armor3_value' => ['numeric'],

            'character_shield_type' => ['string'],
            'character_shield_physic' => ['numeric'],
            'character_shield_field' => ['numeric'],
            'character_shield_face' => ['numeric'],
            'character_shield_flank' => ['numeric'],
            'character_shield_back' => ['numeric'],
            'character_shield_value' => ['numeric'],

            'character_equipped_spellbook' => ['string'],
            'character_equipped_spellbook_value' => ['numeric'],

            'character_equipped_symbol' => ['string'],
            'character_equipped_symbol_value' => ['numeric'],

            'character_tma_alcool' => ['numeric'],
            'character_tma_alcool_b' => ['numeric'],
            'character_tma_arts&crafts' => ['numeric'],
            'character_tma_arts&crafts_b' => ['numeric'],
            'character_tma_carpentry' => ['numeric'],
            'character_tma_carpentry_b' => ['numeric'],
            'character_tma_hunting&fishing' => ['numeric'],
            'character_tma_hunting&fishing_b' => ['numeric'],
            'character_tma_drive' => ['numeric'],
            'character_tma_drive_b' => ['numeric'],
            'character_tma_strings' => ['numeric'],
            'character_tma_strings_b' => ['numeric'],
            'character_tma_run' => ['numeric'],
            'character_tma_run_b' => ['numeric'],
            'character_tma_balanced' => ['numeric'],
            'character_tma_balanced_b' => ['numeric'],
            'character_tma_horseriding' => ['numeric'],
            'character_tma_horseriding_b' => ['numeric'],
            'character_tma_climbing' => ['numeric'],
            'character_tma_climbing_b' => ['numeric'],
            'character_tma_fight' => ['numeric'],
            'character_tma_fight_b' => ['numeric'],
            'character_tma_metallurgy' => ['numeric'],
            'character_tma_metallurgy_b' => ['numeric'],
            'character_tma_swimming' => ['numeric'],
            'character_tma_swimming_b' => ['numeric'],
            'character_tma_navigation' => ['numeric'],
            'character_tma_navigation_b' => ['numeric'],
            'character_tma_torture' => ['numeric'],
            'character_tma_torture_b' => ['numeric'],
            'character_tma_dragonry' => ['numeric'],
            'character_tma_dragonry_b' => ['numeric'],

            'character_tha_acrobatics' => ['numeric'],
            'character_tha_acrobatics_b' => ['numeric'],
            'character_tha_naturecamo' => ['numeric'],
            'character_tha_naturecamo_b' => ['numeric'],
            'character_tha_urbancamo' => ['numeric'],
            'character_tha_urbancamo_b' => ['numeric'],
            'character_tha_lockpicking' => ['numeric'],
            'character_tha_lockpicking_b' => ['numeric'],
            'character_tha_disguise' => ['numeric'],
            'character_tha_disguise_b' => ['numeric'],
            'character_tha_demolition' => ['numeric'],
            'character_tha_demolition_b' => ['numeric'],
            'character_tha_discretnature' => ['numeric'],
            'character_tha_discretnature_b' => ['numeric'],
            'character_tha_discreturban' => ['numeric'],
            'character_tha_discreturban_b' => ['numeric'],
            'character_tha_concealment' => ['numeric'],
            'character_tha_concealment_b' => ['numeric'],
            'character_tha_medecine' => ['numeric'],
            'character_tha_medecine_b' => ['numeric'],
            'character_tha_trap' => ['numeric'],
            'character_tha_trap_b' => ['numeric'],
            'character_tha_precision' => ['numeric'],
            'character_tha_precision_b' => ['numeric'],
            'character_tha_technology' => ['numeric'],
            'character_tha_technology_b' => ['numeric'],
            'character_tha_thanatology' => ['numeric'],
            'character_tha_thanatology_b' => ['numeric'],
            'character_tha_pickpocketing' => ['numeric'],
            'character_tha_pickpocketing_b' => ['numeric'],
            'character_tha_tribaltattoo' => ['numeric'],
            'character_tha_tribaltattoo_b' => ['numeric'],

            'character_tse_analysis' => ['numeric'],
            'character_tse_analysis_b' => ['numeric'],
            'character_tse_concentration' => ['numeric'],
            'character_tse_concentration_b' => ['numeric'],
            'character_tse_cook' => ['numeric'],
            'character_tse_cook_b' => ['numeric'],
            'character_tse_detection' => ['numeric'],
            'character_tse_detection_b' => ['numeric'],
            'character_tse_dressage' => ['numeric'],
            'character_tse_dressage_b' => ['numeric'],
            'character_tse_listen' => ['numeric'],
            'character_tse_listen_b' => ['numeric'],
            'character_tse_evaluation' => ['numeric'],
            'character_tse_evaluation_b' => ['numeric'],
            'character_tse_lipreading' => ['numeric'],
            'character_tse_lipreading_b' => ['numeric'],
            'character_tse_meteorology' => ['numeric'],
            'character_tse_meteorology_b' => ['numeric'],
            'character_tse_observation' => ['numeric'],
            'character_tse_observation_b' => ['numeric'],
            'character_tse_smell' => ['numeric'],
            'character_tse_smell_b' => ['numeric'],
            'character_tse_orientation' => ['numeric'],
            'character_tse_orientation_b' => ['numeric'],
            'character_tse_perception' => ['numeric'],
            'character_tse_perception_b' => ['numeric'],
            'character_tse_tracking' => ['numeric'],
            'character_tse_tracking_b' => ['numeric'],
            'character_tse_research' => ['numeric'],
            'character_tse_research_b' => ['numeric'],
            'character_tse_pes' => ['numeric'],
            'character_tse_pes_b' => ['numeric'],

            'character_tso_spiel' => ['numeric'],
            'character_tso_spiel_b' => ['numeric'],
            'character_tso_corruption' => ['numeric'],
            'character_tso_corruption_b' => ['numeric'],
            'character_tso_eloquence' => ['numeric'],
            'character_tso_eloquence_b' => ['numeric'],
            'character_tso_empathy' => ['numeric'],
            'character_tso_empathy_b' => ['numeric'],
            'character_tso_counterfeiting' => ['numeric'],
            'character_tso_counterfeiting_b' => ['numeric'],
            'character_tso_hypnotism' => ['numeric'],
            'character_tso_hypnotism_b' => ['numeric'],
            'character_tso_intimidation' => ['numeric'],
            'character_tso_intimidation_b' => ['numeric'],
            'character_tso_secretjargon' => ['numeric'],
            'character_tso_secretjargon_b' => ['numeric'],
            'character_tso_game' => ['numeric'],
            'character_tso_game_b' => ['numeric'],
            'character_tso_leadership' => ['numeric'],
            'character_tso_leadership_b' => ['numeric'],
            'character_tso_bargaining' => ['numeric'],
            'character_tso_bargaining_b' => ['numeric'],
            'character_tso_performance' => ['numeric'],
            'character_tso_performance_b' => ['numeric'],
            'character_tso_rumors' => ['numeric'],
            'character_tso_rumors_b' => ['numeric'],
            'character_tso_seduction' => ['numeric'],
            'character_tso_seduction_b' => ['numeric'],
            'character_tso_ventriloquism' => ['numeric'],
            'character_tso_ventriloquism_b' => ['numeric'],
            'character_tso_ignisalta' => ['numeric'],
            'character_tso_ignisalta_b' => ['numeric'],

            'character_tco_ancientcult' => ['numeric'],
            'character_tco_ancientcult_b' => ['numeric'],
            'character_tco_astronomy' => ['numeric'],
            'character_tco_astronomy_b' => ['numeric'],
            'character_tco_library' => ['numeric'],
            'character_tco_library_b' => ['numeric'],
            'character_tco_creature' => ['numeric'],
            'character_tco_creature_b' => ['numeric'],
            'character_tco_geography' => ['numeric'],
            'character_tco_geography_b' => ['numeric'],
            'character_tco_history' => ['numeric'],
            'character_tco_history_b' => ['numeric'],
            'character_tco_identification' => ['numeric'],
            'character_tco_identification_b' => ['numeric'],
            'character_tco_houses' => ['numeric'],
            'character_tco_houses_b' => ['numeric'],
            'character_tco_nature' => ['numeric'],
            'character_tco_nature_b' => ['numeric'],
            'character_tco_occultism' => ['numeric'],
            'character_tco_occultism_b' => ['numeric'],
            'character_tco_politics' => ['numeric'],
            'character_tco_politics_b' => ['numeric'],
            'character_tco_ritualofdeath' => ['numeric'],
            'character_tco_ritualofdeath_b' => ['numeric'],
            'character_tco_spell' => ['numeric'],
            'character_tco_spell_b' => ['numeric'],
            'character_tco_tactical' => ['numeric'],
            'character_tco_tactical_b' => ['numeric'],
            'character_tco_theology' => ['numeric'],
            'character_tco_theology_b' => ['numeric'],
            'character_tco_ritualofstars' => ['numeric'],
            'character_tco_ritualofstars_b' => ['numeric'],

            'character_influence_meraltor' => ['required', 'numeric', 'min:0'],
            'character_influence_aravas' => ['required', 'numeric', 'min:0'],
            'character_influence_clergy' => ['required', 'numeric', 'min:0'],
            'character_influence_berrouve' => ['required', 'numeric', 'min:0'],
            'character_influence_harlog' => ['required', 'numeric', 'min:0'],
            'character_influence_brotherhood' => ['required', 'numeric', 'min:0'],
            'character_influence_duloir' => ['required', 'numeric', 'min:0'],
            'character_influence_tiar' => ['required', 'numeric', 'min:0'],
            'character_influence_wolfcircle' => ['required', 'numeric', 'min:0'],
            'character_influence_arcadis' => ['required', 'numeric', 'min:0'],
            'character_influence_komeidai' => ['required', 'numeric', 'min:0'],
            'character_influence_savie' => ['required', 'numeric', 'min:0'],
            'character_influence_mortuterra' => ['required', 'numeric', 'min:0'],
            'character_influence_collectorsguild' => ['required', 'numeric', 'min:0'],
            'character_influence_total' => ['required', 'numeric' , 'min:0', 'max:500'],

            'character_background' => ['string'],

            'character_injury1_name' => ['string'],
            'character_injury1_descr' => ['string'],
            'character_injury1_year' => ['numeric'],
            'character_injury1_month' => ['numeric'],
            'character_injury1_day' => ['numeric'],

            'character_injury2_name' => ['string'],
            'character_injury2_descr' => ['string'],
            'character_injury2_year' => ['numeric'],
            'character_injury2_month' => ['numeric'],
            'character_injury2_day' => ['numeric'],

            'character_injury3_name' => ['string'],
            'character_injury3_descr' => ['string'],
            'character_injury3_year' => ['numeric'],
            'character_injury3_month' => ['numeric'],
            'character_injury3_day' => ['numeric'],

            'character_injury4_name' => ['string'],
            'character_injury4_descr' => ['string'],
            'character_injury4_year' => ['numeric'],
            'character_injury4_month' => ['numeric'],
            'character_injury4_day' => ['numeric'],

            'character_injury5_name' => ['string'],
            'character_injury5_descr' => ['string'],
            'character_injury5_year' => ['numeric'],
            'character_injury5_month' => ['numeric'],
            'character_injury5_day' => ['numeric'],

            'character_injury6_name' => ['string'],
            'character_injury6_descr' => ['string'],
            'character_injury6_year' => ['numeric'],
            'character_injury6_month' => ['numeric'],
            'character_injury6_day' => ['numeric'],

            'character_injury7_name' => ['string'],
            'character_injury7_descr' => ['string'],
            'character_injury7_year' => ['numeric'],
            'character_injury7_month' => ['numeric'],
            'character_injury7_day' => ['numeric'],

            'character_injury8_name' => ['string'],
            'character_injury8_descr' => ['string'],
            'character_injury8_year' => ['numeric'],
            'character_injury8_month' => ['numeric'],
            'character_injury8_day' => ['numeric'],

            'character_scar1_name' => ['string'],
            'character_scar1_descr' => ['string'],
            'character_scar1_year' => ['numeric'],
            'character_scar1_month' => ['numeric'],
            'character_scar1_day' => ['numeric'],

            'character_scar2_name' => ['string'],
            'character_scar2_descr' => ['string'],
            'character_scar2_year' => ['numeric'],
            'character_scar2_month' => ['numeric'],
            'character_scar2_day' => ['numeric'],

            'character_scar3_name' => ['string'],
            'character_scar3_descr' => ['string'],
            'character_scar3_year' => ['numeric'],
            'character_scar3_month' => ['numeric'],
            'character_scar3_day' => ['numeric'],

            'character_scar4_name' => ['string'],
            'character_scar4_descr' => ['string'],
            'character_scar4_year' => ['numeric'],
            'character_scar4_month' => ['numeric'],
            'character_scar4_day' => ['numeric'],

            'character_scar5_name' => ['string'],
            'character_scar5_descr' => ['string'],
            'character_scar5_year' => ['numeric'],
            'character_scar5_month' => ['numeric'],
            'character_scar5_day' => ['numeric'],

            'character_scar6_name' => ['string'],
            'character_scar6_descr' => ['string'],
            'character_scar6_year' => ['numeric'],
            'character_scar6_month' => ['numeric'],
            'character_scar6_day' => ['numeric'],

            'character_scar7_name' => ['string'],
            'character_scar7_descr' => ['string'],
            'character_scar7_year' => ['numeric'],
            'character_scar7_month' => ['numeric'],
            'character_scar7_day' => ['numeric'],

            'character_scar8_name' => ['string'],
            'character_scar8_descr' => ['string'],
            'character_scar8_year' => ['numeric'],
            'character_scar8_month' => ['numeric'],
            'character_scar8_day' => ['numeric'],

            'character_deco1_name' => ['string'],
            'character_deco1_descr' => ['string'],
            'character_deco1_year' => ['numeric'],
            'character_deco1_month' => ['numeric'],
            'character_deco1_day' => ['numeric'],

            'character_deco2_name' => ['string'],
            'character_deco2_descr' => ['string'],
            'character_deco2_year' => ['numeric'],
            'character_deco2_month' => ['numeric'],
            'character_deco2_day' => ['numeric'],

            'character_deco3_name' => ['string'],
            'character_deco3_descr' => ['string'],
            'character_deco3_year' => ['numeric'],
            'character_deco3_month' => ['numeric'],
            'character_deco3_day' => ['numeric'],

            'character_deco4_name' => ['string'],
            'character_deco4_descr' => ['string'],
            'character_deco4_year' => ['numeric'],
            'character_deco4_month' => ['numeric'],
            'character_deco4_day' => ['numeric'],

            'character_deco5_name' => ['string'],
            'character_deco5_descr' => ['string'],
            'character_deco5_year' => ['numeric'],
            'character_deco5_month' => ['numeric'],
            'character_deco5_day' => ['numeric'],

            'character_deco6_name' => ['string'],
            'character_deco6_descr' => ['string'],
            'character_deco6_year' => ['numeric'],
            'character_deco6_month' => ['numeric'],
            'character_deco6_day' => ['numeric'],

            'character_deco7_name' => ['string'],
            'character_deco7_descr' => ['string'],
            'character_deco7_year' => ['numeric'],
            'character_deco7_month' => ['numeric'],
            'character_deco7_day' => ['numeric'],

            'character_deco8_name' => ['string'],
            'character_deco8_descr' => ['string'],
            'character_deco8_year' => ['numeric'],
            'character_deco8_month' => ['numeric'],
            'character_deco8_day' => ['numeric'],

        ];
    }
}
