<?php

namespace App\Models\Chapitre\Sept;

use Illuminate\Database\Eloquent\Model;

class CommercialProduct extends Model
{
    protected $fillable = [

        'citesDataCommProdTitle',
        'citesDataCommProdText',

        'citesDataCommProdMinTabTitleName',
        'citesDataCommProdMinTabTitleKilo',
        'citesDataCommProdMinTableMin1',
        'citesDataCommProdMinTabMin1Kilo',
        'citesDataCommProdMinTabMin2',
        'citesDataCommProdMinTabMin2Kilo',
        'citesDataCommProdMinTabMin3',
        'citesDataCommProdMinTabMin3Kilo',
        'citesDataCommProdMinTabMin4',
        'citesDataCommProdMinTabMin4Kilo',
        'citesDataCommProdMinTabMin5',
        'citesDataCommProdMinTabMin5Kilo',
        'citesDataCommProdMinTabMin6',
        'citesDataCommProdMinTabMin6Kilo',
        'citesDataCommProdMinTabMin7',
        'citesDataCommProdMinTabMin7Kilo',
        'citesDataCommProdMinTableMin8',
        'citesDataCommProdMinTabMin8Kilo',
        'citesDataCommProdMinTabMin9',
        'citesDataCommProdMinTabMin9Kilo',
        'citesDataCommProdMinTabMin10',
        'citesDataCommProdMinTabMin10Kilo',

        'citesDataCommProdVegTabTitleName',
        'citesDataCommProdVegTabTitleKilo',
        'citesDataCommProdVegTabVeg1',
        'citesDataCommProdVegTabVeg1Kilo',
        'citesDataCommProdVegTabVeg2',
        'citesDataCommProdVegTabVeg2Kilo',
        'citesDataCommProdVegTabVeg3',
        'citesDataCommProdVegTabVeg3Kilo',
        'citesDataCommProdVegTabVeg4',
        'citesDataCommProdVegTabVeg4Kilo',
        'citesDataCommProdVegTabVeg5',
        'citesDataCommProdVegTabVeg5Kilo',
        'citesDataCommProdVegTabVeg6',
        'citesDataCommProdVegTabVeg6Kilo',
        'citesDataCommProdVegTabVeg7',
        'citesDataCommProdVegTabVeg7Kilo',
        'citesDataCommProdVegTabVeg8',
        'citesDataCommProdVegTabVeg8Kilo',
        'citesDataCommProdVegTabVeg9',
        'citesDataCommProdVegTabVeg9Kilo',
        'citesDataCommProdVegTabVeg10',
        'citesDataCommProdVegTabVeg10Kilo',

        'citesDataCommProdAniTabTitleName',
        'citesDataCommProdAniTabTitleKilo',
        'citesDataCommProdAniTabAni1',
        'citesDataCommProdAniTabAni1Kilo',
        'citesDataCommProdAniTabAni2',
        'citesDataCommProdAniTabAni2Kilo',
        'citesDataCommProdAniTabAni3',
        'citesDataCommProdAniTabAni3Kilo',
        'citesDataCommProdAniTabAni4',
        'citesDataCommProdAniTabAni4Kilo',
        'citesDataCommProdAniTabAni5',
        'citesDataCommProdAniTabAni5Kilo',
        'citesDataCommProdAniTabAni6',
        'citesDataCommProdAniTabAni6Kilo',
        'citesDataCommProdAniTabAni7',
        'citesDataCommProdAniTabAni7Kilo',
        'citesDataCommProdAniTabAni8',
        'citesDataCommProdAniTabAni8Kilo',
        'citesDataCommProdAniTabAni9',
        'citesDataCommProdAniTabAni9Kilo',
        'citesDataCommProdAniTabAni10',
        'citesDataCommProdAniTabAni10Kilo',

        'citesDataCommProdConTabTitleName',
        'citesDataCommProdConTabTitleKilo',
        'citesDataCommProdConTabCon1',
        'citesDataCommProdConTabCon1Kilo',
        'citesDataCommProdConTabCon2',
        'citesDataCommProdConTabCon2Kilo',
        'citesDataCommProdConTabCon3',
        'citesDataCommProdConTabCon3Kilo',
        'citesDataCommProdConTabCon4',
        'citesDataCommProdConTabCon4Kilo',
        'citesDataCommProdConTabCon5',
        'citesDataCommProdConTabCon5Kilo',
        'citesDataCommProdConTabCon6',
        'citesDataCommProdConTabCon6Kilo',
        'citesDataCommProdConTabCon7',
        'citesDataCommProdConTabCon7Kilo',
        'citesDataCommProdConTabCon8',
        'citesDataCommProdConTabCon8Kilo',
        'citesDataCommProdConTabCon9',
        'citesDataCommProdConTabCon9Kilo',
        'citesDataCommProdConTabCon10',
        'citesDataCommProdConTabCon10Kilo',

        'citesDataCommProdSusTabTitleName',
        'citesDataCommProdSusTabTitleKilo',
        'citesDataCommProdSusTabSus1',
        'citesDataCommProdSusTabSus1Kilo',
        'citesDataCommProdSusTabSus2',
        'citesDataCommProdSusTabSus2Kilo',
        'citesDataCommProdSusTabSus3',
        'citesDataCommProdSusTabSus3Kilo',
        'citesDataCommProdSusTabSus4',
        'citesDataCommProdSusTabSus4Kilo',
        'citesDataCommProdSusTabSus5',
        'citesDataCommProdSusTabSus5Kilo',
        'citesDataCommProdSusTabSus6',
        'citesDataCommProdSusTabSus6Kilo',
        'citesDataCommProdSusTabSus7',
        'citesDataCommProdSusTabSus7Kilo',
        'citesDataCommProdSusTabSus8',
        'citesDataCommProdSusTabSus8Kilo',
        'citesDataCommProdSusTabSus9',
        'citesDataCommProdSusTabSus9Kilo',
        'citesDataCommProdSusTabSus10',
        'citesDataCommProdSusTabSus10Kilo',

        'citesDataCommProdTextExplain'
    ];
}
