<?php

namespace App\models;

use Illuminate\Database\Eloquent\Model;

class CityText extends Model

{
    protected $fillable = [
        'cityTitle',
        'cityText',
        'cityDataTitle',
        'cityDataDescriptionTitle',
        'cityDataName',
        'cityDataNameDescription',
        'cityDataHouse',
        'cityDataHouseDescription',
        'cityDataFoundation',
        'cityDataFoundationDescription',
        'cityDataSize',
        'cityDataSizeDescription',
        'cityDataAccent',
        'cityDataAccentDescription',
        'cityDataUrbanPopulation',
        'cityDataUrbanPopulationDescription',
        'cityDataRuralPopulation',
        'cityDataRuralPolulationDescription',
        'cityDataMaxTrade',
        'cityDataMaxTradeDescription',
        'cityDataLocalDrink',
        'cityDataLocalDescription',
        'cityDataMayor',
        'cityDataMayorDescription',
        'cityDataEconomy',
        'cityDataEconomyDescription',
        'cityDataOffert',
        'cityDataOfferDescription',
        'cityDataDemand',
        'cityDataDemandDescription',
        'cityDataNextOfferts',
        'cityDataNextOffertsDescription',
        'cityDataNextDemands',
        'cityDataNextDemandsDescription',
        'cityDataPointsText',
        'cityDataNoteName',
        'cityDataNoteDescriptionName',
        'cityDataNoteEducation',
        'cityDataNoteEducationDescription',
        'cityDataNoteFortification',
        'cityDataNoteFortificationDescription',
        'cityDataNoteLawAndOrder',
        'cityDataNoteLawAndOrderDescription',
        'cityDataNoteTechnology',
        'cityDataNoteTechnologyDescription',
        'cityDataNoteWealth',
        'cityDataNoteWealthDescription',
        'cityDataTimeTravelTitle',
        'cityDataTimeTravelText',
        'cityDataTimeTravelNDOF1',
        'cityDataTimeTravelNDOF2',
        'cityDataTimeTravelNDOF3',
        'cityDataTimeTravelNDOF4',
        'cityDataTimeTravelNDOF5',
        'cityDataTimeTravelNDOF6',
        'cityDataTimeTravelNDOF7',
        'cityDataTimeTravelNDOF8',
        'cityDataTimeTravelNDOF9',
        'cityDataTimeTravelNDOF10',
        'cityDataTimeTravelNDOF11',
        'cityDataTimeTravelNDOF12',
        'cityDataTimeTravelNDOF13',
        'cityDataTimeTravelNDOF14',
        'cityDataTimeTravelNDOF15',
        'cityDataTimeTravelNDOM1',
        'cityDataTimeTravelNDOM2',
        'cityDataTimeTravelNDOM3',
        'cityDataTimeTravelNDOM4',
        'cityDataTimeTravelNDOM5',
        'cityDataTimeTravelNDOM6',
        'cityDataTimeTravelNDOM7',
        'cityDataTimeTravelNDOM8',
        'cityDataTimeTravelNDOM9',
        'cityDataTimeTravelNDOM10',
        'cityDataTimeTravelNDOM11',
        'cityDataTimeTravelNDOM12',
        'cityDataTimeTravelNDOM13',
        'cityDataTimeTravelNDOM14',
        'cityDataTimeTravelNDOM15',
        'cityDataTimeTravelText2',
        'cityDataOffertDemandTitle',
        'cityDataOffertDemandText',
        'cityDataOffertDemandBuytitle',
        'cityDataOffertDemandBuytext',
        'cityDataOffertDemandSellTitle',
        'cityDataOffertDemandSellText',







    ];
}
